
BLENDER="F:\steam game\steamapps\common\Blender\blender.exe"
DIST=../dist

all : \
    $(DIST)/jumpingland.pnct \
    $(DIST)/jumpingland.scene \

$(DIST)/jumpingland.scene : jumpingland.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "jumpingland.blend:Main" "$(DIST)/jumpingland.scene"

$(DIST)/jumpingland.pnct : jumpingland.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "jumpingland.blend:Main" "$(DIST)/jumpingland.pnct" 
